scheduler: 
    check_period_sec: 60
    event_ttl_days: 365
    
database:
  host: "localhost"
  port: "5433"
  user: "postgres"
  database: "events_db"
  ssl: "disable"
  max_opened_connections: 10

rabbit_producer:
  dsn: "amqp://guest:guest@queue:5672/"
  queue_name": "events"

logger:
  env: "dev"