version: "3"
volumes:
  postgres-volume:

services:
  postgres:
    image: postgres:14-alpine3.15
    container_name: 'event_storage'
    environment:
      - "POSTGRES_DB=events_db"
      - "POSTGRES_PASSWORD=event_pass"
      - "POSTGRES_USER=postgres"
      - "PGDATA=/var/lib/postgresql/data/notification"
    volumes: 
      - postgres-volume:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build: ./deploy/scheduler
    image: nikitads9/event-schedule:scheduler
    container_name: 'scheduler'
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    links:
      - postgres