version: "3.8"

networks:
  app_net:
    driver: bridge

volumes:
  postgres-volume:

services:
  db:
    container_name: event_storage
    image: postgres:16-alpine3.19
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "PGDATA=${PGDATA}"
    expose:
    - "${DB_PORT}" 
    volumes: 
      - postgres-volume:/var/lib/postgresql/data
    #  - ./deploy/database/init.sql:/docker-entrypoint-initdb.d/init.sql 
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: -p ${DB_PORT}
    networks:
      - app_net

  events:
    container_name: events
    build:
      context: .
      dockerfile: ./deploy/events/Dockerfile
    image: nikitads9/event-schedule:events
    ports:
      - "${EVENTS_PORT}:${EVENTS_PORT}"
    depends_on:
      - db
    networks:
      - app_net

  migrator:
    container_name: migrator
    build: $MIGRATION_DIR
    restart: on-failure
    environment:
      - "GOOSE_DRIVER=postgres"
      - "GOOSE_DBSTRING=host=${DB_HOST} port=${DB_PORT} dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} sslmode=${DB_SSL}"
      - "MIGRATION_DIR=${MIGRATION_DIR}"
    ports:
      - "5446:5433"
    depends_on:
      - db
    networks:
      - app_net

  scheduler:
    container_name: scheduler
    build:
      context: .
      dockerfile: ./deploy/scheduler/Dockerfile
    restart: on-failure
    environment:
      - "DB_NAME=${DB_NAME}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_HOST=${DB_HOST}"
    depends_on:
      - db
      - queue
    networks:
      - app_net

  sender:
    container_name: sender
    build:
      context: .
      dockerfile: ./deploy/sender/Dockerfile
    restart: on-failure
    depends_on:
      - queue
    networks:
      - app_net

  queue:
    container_name: queue
    image: rabbitmq:3-management-alpine
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - app_net