version: "3.8"

networks:
  app_net:
    driver: bridge

volumes:
  postgres-volume:

services:
  db:
    image: postgres:14-alpine3.19
    container_name: 'event_storage'
    environment:
      - "POSTGRES_DB=events_db"
      - "POSTGRES_PASSWORD=event_pass"
      - "POSTGRES_USER=postgres"
      - "PGDATA=/var/lib/postgresql/data/notification"
    volumes: 
      - postgres-volume:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app_net

  app:
    build:
      context: .
      dockerfile: ./deploy/scheduler/Dockerfile
    image: nikitads9/event-schedule:scheduler
    container_name: 'scheduler'
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app_net