receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 1m
        static_configs:
        - targets: ['booking:3000','auth:5000']
exporters:
  prometheus/traces:
    endpoint: 0.0.0.0:8889 # metrics got from spans
  prometheus:
    endpoint: 0.0.0.0:8890 # metrics got from apps meters
  otlp/jaeger: 
    endpoint: http://jaeger:4317
    tls:
      insecure: true

processors:
  batch:

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [2ms, 8ms, 50ms, 100ms, 200ms, 500ms, 1s, 5s, 10s]
    dimensions_cache_size: 100000
    aggregation_temporality: AGGREGATION_TEMPORALITY_CUMULATIVE
    dimensions:
      - name: http.method
      
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger,spanmetrics]
    metrics/traces:
      receivers: [otlp,spanmetrics]
      processors: []
      exporters: [prometheus/traces]
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheus]
