// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package booking

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID        pgtype.UUID      `db:"id"`
	StartDate pgtype.Timestamp `db:"start_date"`
	EndDate   pgtype.Timestamp `db:"end_date"`
	NotifyAt  pgtype.Interval  `db:"notify_at"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at"`
	SuiteID   int64            `db:"suite_id"`
	UserID    int64            `db:"user_id"`
}

type Room struct {
	ID       int64       `db:"id"`
	Capacity int32       `db:"capacity"`
	Name     pgtype.Text `db:"name"`
}

type User struct {
	ID               int64            `db:"id"`
	Name             string           `db:"name"`
	TelegramID       int64            `db:"telegram_id"`
	TelegramNickname string           `db:"telegram_nickname"`
	Password         string           `db:"password"`
	CreatedAt        pgtype.Timestamp `db:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at"`
}
