server:
  port: ":3000"
  timeout: 6s
  idle_timeout: 30s

database:
  host: "localhost"
  port: "5433"
  user: "postgres"
  database: "events_db"
  ssl: "disable"
  max_opened_connections: 10

jwt:
  secret: "verysecretivejwt"
  expiration: 2160h
  
env: "dev"