scheduler: 
    check_period_sec: 60
    booking_ttl_days: 365
    
database:
  host: "db"
  port: "5433"
  user: "postgres"
  database: "bookings_db"
  ssl: "disable"
  max_opened_connections: 10

rabbit_producer:
  dsn: "amqp://guest:guest@queue:5672/bookings"
  queue_name: "bookings"

env: "dev"

tracer:
  endpoint_url: "http://jaeger:4318/v1/traces"
  sampling_rate: 1.0