server:
  env: "dev"
  host: "127.0.0.1"
  port: ":3000"
  timeout: 10s
  idle_timeout: 30s

database:
  host: "postgres"
  port: "5432"
  user: "postgres"
  database: "segments_db"
  ssl: "disable"
  max_opened_connections: 10