name: stats

on:
    push:
      branches: [ main]
    pull_request:
      branches: [ main ]
      
jobs:
    scc_job:
      runs-on: ubuntu-latest
      name: A job to count the lines of code.
      permissions:
        id-token: write 
        contents: write
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Get the lines of code.
          id: scc
          uses: iryanbell/scc-docker-action@v1.0.2
          with:
            args: ${{ env.workspace }} --exclude-dir docs,LICENSE,README.md --gen --no-gen --format json .
        - name: Write Badge
          uses: action-badges/core@0.3.0
          with:
            file-name: lines.svg
            github-token: "${{ secrets.GITHUB_TOKEN }}"
            badge-branch: badges
            label: code lines
            message: ${{ fromJson(steps.scc.outputs.scc)[0].Code }}
            message-color: blue